---
# plugin installation tasks for ansible-role-vim.

- name: Clone {{ plugin_data.type }} plugins into place.
  git:
    clone: true
    dest: "{{ '/home/' if (plugin.1!='root') else '/' }}{{ plugin.1 }}/.vim/pack/{{ plugin_data.directory }}/{{ (plugin.0.repo | basename | splitext)[0] }}"
    # When updating, do so even if there are local changes to the repo (this
    # happens when we generate helptags for Vim).
    force: true
    repo: "{{ plugin.0.repo }}"
    # Update when needed (in practice, this will happen only when 'version' is
    # set to 'master' or 'HEAD').
    update: true
    version: "{{ plugin.version | default('HEAD') }}"
  become: true
  become_user: "{{ plugin.1 }}"
  loop: "{{ plugin_data.list | product( plugin_data.users ) | list }}"
  loop_control:
    loop_var: plugin
  tags:
    - molecule-idempotence-notest

- name: Create/update helptags for {{ plugin_data.type }} plugins.
  shell: "vim -c 'helptags .' -c q"
  args:
    chdir: "{{ '/home/' if (plugin.1!='root') else '/' }}{{ plugin.1 }}/.vim/pack/{{ plugin_data.directory }}/{{ (plugin.0.repo | basename | splitext)[0] }}/doc"
  become: true
  become_user: "{{ plugin.1 }}"
  loop: "{{ plugin_data.list | product( plugin_data.users ) | list }}"
  loop_control:
    loop_var: plugin
  tags:
    - molecule-idempotence-notest
