---
# tasks file for ansible-role-vim.

- name: Perform package install and removal for Vim and Vim plugin install.
  include_tasks: "manage-packages.yml"

- name: Perform setup tasks for Vim and Vim plugin install.
  include_tasks: "setup.yml"

- name: Perform dotfile installation for Vim.
  include_tasks: "copy-dotfiles.yml"

- name: Peform Vim plugin installation.
  include_tasks: "install-plugins.yml"
  loop:
    - list: "{{ vim_start_installed_plugins }}"
      directory: "{{ vim_pack_start_subdirectory }}"
      type: "start"
      users: "{{ vim_users + vim_users_host_vars }}"
    - list: "{{ vim_opt_installed_plugins }}"
      directory: "{{ vim_pack_opt_subdirectory }}"
      type: "opt"
      users: "{{ vim_users + vim_users_host_vars }}"
  loop_control:
    loop_var: plugin_data

- name: Perform Vim plugin removal.
  include_tasks: "remove-plugins.yml"
  loop:
    - list: "{{ vim_start_removed_plugins }}"
      directory: "{{ vim_pack_start_subdirectory }}"
      type: "start"
      users: "{{ vim_users + vim_users_host_vars }}"
    - list: "{{ vim_opt_removed_plugins }}"
      directory: "{{ vim_pack_opt_subdirectory }}"
      type: "opt"
      users: "{{ vim_users + vim_users_host_vars }}"
  loop_control:
    loop_var: plugin_data
