---
# plugin removal tasks for ansible-role-vim.

- name: Remove {{ plugin_data.type }} plugins.
  file:
    path: "{{ '/home/' if (plugin.1!='root') else '/' }}{{ plugin.1 }}/.vim/pack/{{ plugin_data.directory }}/{{ (plugin.0.repo | basename | splitext)[0] }}"
    state: absent
  become: true
  become_user: "{{ plugin.1 }}"
  loop: "{{ plugin_data.list | product( plugin_data.users ) | list }}"
  loop_control:
    loop_var: plugin
  tags:
    - molecule-idempotence-notest
