# setup tasks for ansible-role-vim.

- name: Get Vim version.
  shell: "set -o pipefail && vim --version | head -n1 | awk '{ print $5 }'"
  args:
    executable: "/bin/bash"
  register: vim_version_string
  changed_when: false

- name: Make sure it even makes sense to continue.
  assert:
    that: "{{ vim_version_string.stdout is version('8.0', '>=') }}"
    msg: "Vim does not support native package management in versions lower than 8.0."

- name: Determine Vim start plugin directory.
  set_fact:
    vim_pack_start_subdirectory: "{{ vim_pack_subdirectory }}/start"

- name: Determine Vim opt plugin directory.
  set_fact:
    vim_pack_opt_subdirectory: "{{ vim_pack_subdirectory }}/opt"
